# =============================================================================
# config.R
# =============================================================================
# Set the paths and binaries below, then run the main script:
#
#   macOS:     double-click run_all.command   (or:  Rscript run_all.R)
#   Windows:   double-click run_all.bat       (or:  Rscript run_all.R)
#
# =============================================================================

# --- Paths --------------------------------------------------------------------
# PROJECT_ROOT is the absolute path to your local clone of this repo.
PROJECT_ROOT <- "/path/to/your/repo" # I used "D:/Users/gaubrac/Desktop/newer-glp1-dementia-repkit"

DATA_DIR    <- file.path(PROJECT_ROOT, "data")        # input data (not used directly)
OUTPUT_DIR  <- file.path(PROJECT_ROOT, "output")      # intermediate files
RESULTS_DIR <- Sys.getenv("RESULTS_DIR", unset = file.path(PROJECT_ROOT, "results"))

# --- Study period -------------------------------------------------------------
# Study start and end dates. Update to change study window. 
# Read by 03-identify-new-users.qmd (cohort entry),
# 05-extract-coverage-indicator.do (eligibility-end cutoff), and
# 18-run-survival-analyses.qmd
STUDY_START <- "2022-05-01"
STUDY_END   <- "2026-01-01"
Sys.setenv(STUDY_START = STUDY_START, STUDY_END = STUDY_END)

# --- Binaries -----------------------------------------------------------------
# Either a bare name (resolved on PATH) or an absolute path to the executable.
R_BIN      <- "Rscript" # I used "C:/Program Files/R/R-4.4.2/bin/x64/Rscript.exe"
QUARTO_BIN <- "quarto"

# Stata binary name varies by OS and edition; auto-resolved per platform.
# Override the value on the right of the matching row if your install differs.
STATA_BIN <- switch(
  Sys.info()[["sysname"]],
  Darwin  = "stata-mp",       # macOS, also: "stata-se", "stata"
  Linux   = "stata-mp",       # Linux
  Windows = "StataMP-64",     # Windows, also: "StataSE-64", "Stata-64"; I used "C:/Program Files/Stata18/StataMP-64.exe".
  "stata"
)

# --- Database -----------------------------------------------------------------
# Snowflake DSN name (as configured in Windows ODBC Data Source Administrator).
# Referenced by every .do file's `odbc load` via dsn("$SNOWFLAKE_DSN").
SNOWFLAKE_DSN <- "Snowflake Data 2"

# --- Stata globals ------------------------------------------------------------
# Writes <PROJECT_ROOT>/_globals.do containing one `global X "value"` per
# config entry. Every .do file `include`s this file at the top, so all paths
# and study parameters flow from config.R into Stata without env-var games.
# Written as raw bytes — guarantees no UTF-8 BOM (Stata reports BOMs as
# "ï»¿ is not a valid command name r(199)").
write_globals_do <- function() {
  globals <- list(
    PROJECT_ROOT    = PROJECT_ROOT,
    DATA_DIR        = DATA_DIR,
    OUTPUT_DIR      = OUTPUT_DIR,
    RESULTS_DIR     = RESULTS_DIR,
    STUDY_START     = STUDY_START,
    STUDY_END       = STUDY_END,
    COVERAGE_MONTHS = Sys.getenv("COVERAGE_MONTHS", unset = "12"),
    SCENARIO_NAME   = Sys.getenv("SCENARIO_NAME",   unset = "main"),
    SNOWFLAKE_DSN   = SNOWFLAKE_DSN
  )
  lines <- c(
    "* Auto-generated by config.R, do not edit by hand.",
    "* Regenerated each time the pipeline runs (or when you source config.R).",
    sprintf('global %s "%s"', names(globals), unlist(globals))
  )
  path <- file.path(PROJECT_ROOT, "_globals.do")
  writeBin(charToRaw(paste(lines, collapse = "\n")), path)
  invisible(path)
}